const router = require('express').Router()

router.use('/sections', require('./system/section.routes'))
router.use('/grades', require('./system/grade.routes'))
router.use('/houses', require('./housemeets/house.routes'))
router.use('/squads', require('./activities/squad.routes'))
router.use('/competitions', require('./housemeets/competition.routes'))
router.use('/competition-house-rules', require('./housemeets/competitionHouseRule.routes'))
router.use('/competition-registrations', require('./housemeets/competitionRegistration.routes'))
router.use('/competition-teams', require('./housemeets/competitionTeam.routes'))
router.use('/competition-results', require('./housemeets/competitionResult.routes'))
router.use('/team-selections', require('./housemeets/teamSelection.routes'))
router.use('/grading-schemas', require('./system/gradingSchema.routes'))
router.use('/exam-results', require('./student/examResult.routes'))
router.use('/exams', require('./student/exam.routes'))
router.use('/teachers', require('./staff/teacher.routes'))
router.use('/staff-roles', require('./staff/staffRole.routes'))
router.use('/club-positions', require('./activities/clubPosition.routes'))
router.use('/clubs', require('./activities/club.routes'))
router.use('/students', require('./student/student.routes'))
router.use('/student-talents', require('./student/studentTalent.routes'))
router.use('/student-house-assignments', require('./housemeets/studentHouseAssignment.routes'))
router.use('/teacher-house-assignments', require('./housemeets/teacherHouseAssignment.routes'))
router.use('/prefect-positions', require('./staff/prefectPosition.routes'))
router.use('/prefects', require('./staff/prefect.routes'))
router.use('/events', require('./activities/event.routes'))
router.use('/attendance', require('./student/attendance.routes'))
router.use('/promotion', require('./student/promotion.routes'))
router.use('/parents', require('./student/parent.routes'))
router.use('/parent-student-links', require('./student/parentStudentLink.routes'))
router.use('/reports', require('./student/report.routes'))
router.use('/analytics', require('./student/analytics.routes'))
router.use('/permissions', require('./system/permission.routes'))
router.use('/organization-calendar', require('./system/organization-calendar.routes'))

router.use('/app-users', require('./system/appUser.routes'))
router.use('/roles', require('./system/role.routes'))

module.exports = router
