const router = require('express').Router()

router.use('/sections', require('./section.routes'))
router.use('/grades', require('./grade.routes'))
router.use('/houses', require('./house.routes'))
router.use('/squads', require('./squad.routes'))
router.use('/competitions', require('./competition.routes'))
router.use('/competition-house-rules', require('./competitionHouseRule.routes'))
router.use('/competition-registrations', require('./competitionRegistration.routes'))
router.use('/competition-teams', require('./competitionTeam.routes'))
router.use('/competition-results', require('./competitionResult.routes'))
router.use('/team-selections', require('./teamSelection.routes'))
router.use('/grading-schemas', require('./gradingSchema.routes'))
router.use('/exam-results', require('./examResult.routes'))
router.use('/teachers', require('./teacher.routes'))
router.use('/staff-roles', require('./staffRole.routes'))
router.use('/club-positions', require('./clubPosition.routes'))
router.use('/clubs', require('./club.routes'))
router.use('/students', require('./student.routes'))
router.use('/student-talents', require('./studentTalent.routes'))
router.use('/student-house-assignments', require('./studentHouseAssignment.routes'))
router.use('/teacher-house-assignments', require('./teacherHouseAssignment.routes'))
router.use('/prefect-positions', require('./prefectPosition.routes'))
router.use('/prefects', require('./prefect.routes'))
router.use('/events', require('./event.routes'))
router.use('/attendance', require('./attendance.routes'))
router.use('/promotion', require('./promotion.routes'))
router.use('/parents', require('./parent.routes'))
router.use('/parent-student-links', require('./parentStudentLink.routes'))
router.use('/reports', require('./report.routes'))
router.use('/permissions', require('./permission.routes'))
router.use('/app-users', require('./appUser.routes'))

module.exports = router
